name: Build packages
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: build
        run: |
          pip install Cython wheel setuptools
          python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
